import React from "react";
import ProductsElement from "./ProductsElement";
import CristalizaçãoDePintura from '../assets/Cristalização de Pintura.png';  // Adjust the path as necessary
import CristalizaçãoDeVidros from '../assets/Cristalização de Vidros.png';  // Adjust the path as necessary
import DescontaminaçãoDePintura from '../assets/Descontaminação de Pintura.png';  // Adjust the path as necessary
import HidrataçãoDeCouro from '../assets/Hidratação de Couro.png';  // Adjust the path as necessary
import HigienizaçãoDeArCondicionado from '../assets/Higienização de Ar Condicionado.png';  // Adjust the path as necessary
import HigienizaçãoDeCadeirinha from '../assets/Higienização de cadeirinha.png';  // Adjust the path as necessary
import HigienizaçãoInterna from '../assets/Higienização interna.png';  // Adjust the path as necessary
import LavagemTecnica from '../assets/Lavagem técnica.png';  // Adjust the path as necessary
import LimpezaTecnicaDeMotor from '../assets/LIMPEZA TÉCNICA DE MOTOR.png';  // Adjust the path as necessary
import OxiSanitização from '../assets/Oxi-sanitização.png';  // Adjust the path as necessary
import PelículasAutomotivasInsulfilm from '../assets/Películas automotivas (Insulfilm).png';  // Adjust the path as necessary
import PolimentoAutomotivo from '../assets/POLIMENTO AUTOMOTIVO.png';  // Adjust the path as necessary
import PolimentoDeFarol from '../assets/POLIMENTO DE FAROL.png';  // Adjust the path as necessary
import RevitalizaçãoDePlasticos from '../assets/revitalização de plásticos.png';  // Adjust the path as necessary
import VitrificaçãoDePlásticos from '../assets/VITRIFICAÇÃO  DE PLÁSTICO.png';  // Adjust the path as necessary
import VitrificaçãoFarol from '../assets/VITRIFICAÇÃO FAROL.png';  // Adjust the path as necessary
import VitrificaçãoDePintura from '../assets/VITRIFICAÇÃO PINTURA.png';  // Adjust the path as necessary

const Products = () => {
    return (
        <div className="cardsHub">
            <ProductsElement image={CristalizaçãoDePintura} title={'Cristalização de Pintura'} description={'A cristalização de pintura visa melhorar o aspecto da pintura, realçando o brilho da tinta, além disso, garante uma maior durabilidade ao verniz original da pintura do carro. Deste modo, a lataria acaba ficando menos suscetível a danos externos.'} />
            <ProductsElement image={CristalizaçãoDeVidros} title={'Cristalização de Vidros'} description={'A limpeza e cristalização dos vidros, evita a fixação de sujeiras pesadas e melhora a visibilidade, garantindo mais segurança aos ocupantes do veiculo. Diminui a necessidade de limpezas frequentes.'} />
            <ProductsElement image={DescontaminaçãoDePintura} title={'Descontaminação de Pintura'} description={'Descontaminação de pintura é um processo pela qual se garante remoção de todas as impurezas da pintura, através da aplicação de uma (Clay Bar). Estes contaminantes ficam incrustados na pintura causando danos e possível corrosão do verniz. Contaminantes como resina de árvores, pó de tinta (over spray), piche podem ser removidos também com este procedimento.'} />
            <ProductsElement image={HidrataçãoDeCouro} title={'Hidratação de Couro'} description={'A Hidratação de Couro tem como objetivo hidratar, proteger, revitalizar superfícies de couro natural e sintético. Elimina o falso brilho, realça o semifosco original do couro e prolonga a vida útil das peças, sem danificar ou alterar suas características originais.'} />
            <ProductsElement image={HigienizaçãoDeArCondicionado} title={'Higienização de Ar Condicionado'} description={'A higienização do ar-condicionado limpa profundamente o sistema de circulação de ar, protegendo-o contra diversos tipos de fungos, vírus e bactérias que provocam mau cheiro.'} />
            <ProductsElement image={HigienizaçãoDeCadeirinha} title={'Higienização de Cadeirinha'} description={'A limpeza e higienização completa da cadeirinha elimina sujeira, mau cheiro e bactérias que podem fazer mal para o bebê ou criança.'} />
            <ProductsElement image={HigienizaçãoInterna} title={'Higienização Interna'} description={`A higienização interna automotiva é o processo de limpeza e desinfecção da parte interna do veículo. O objetivo é remover sujeiras, manchas, odores desagradáveis e microrganismos, proporcionando um ambiente limpo, saudável e agradável para os ocupantes do veículo. <br> <br> Esse cuidado é importante não apenas do ponto de vista estético, mas também para promover a saúde e o bem-estar dos passageiros. Sem ele, pode haver acúmulo de poeira, ácaros, bactérias, vírus e outros alérgenos que podem afetar a qualidade do ar e causar desconforto.`} />
            <ProductsElement image={LavagemTecnica} title={'Lavagem Técnica'} description={'A Lavagem Técnica é uma lavagem detalhada na qual utilizamos maquinário de última geração, técnicas avançadas e produtos de altíssima qualidade, realizamos uma limpeza interna e externa minuciosa do seu veículo, focada na remoção de sujeiras em áreas de difícil acesso, sem comprometer a integridade da pintura. Além disso, aplicamos uma proteção na pintura para facilitar futuras lavagens e prolongar o intervalo entre elas.'} />
            <ProductsElement image={LimpezaTecnicaDeMotor} title={'Limpeza Técnica de Motor'} description={'A Limpeza Técnica de Motor é um procedimento especializado voltado para a remoção de sujeiras, resíduos e contaminantes acumulados no compartimento do motor. Ao longo do tempo, poeira, óleo, graxa e outros detritos podem se acumular, comprometendo o desempenho do motor e a estética do veículo.'} />
            <ProductsElement image={OxiSanitização} title={'Oxi-Sanitização'} description={'Seu carro está com mau odor? Esse serviço é para você que deseja eliminar qualquer cheiro desagradável de seu veículo. A RR Stetic oferece o serviço de oxi-sanitização, inovação na área de limpeza automotiva que emprega uma máquina específica, capaz de liberar ozônio em seu veículo, o entregando livre de odores, vírus, bactérias e fungos presentes em seu carro.'} />
            <ProductsElement image={PelículasAutomotivasInsulfilm} title={'Películas Automotivas (Insulfilm)'} description={'O insulfilm automotivo é uma película aplicada aos vidros dos veículos com o objetivo de melhorar o conforto, a segurança e a estética. Disponível em diferentes níveis de transparência e tipos de proteção, o insulfilm oferece uma série de benefícios para os motoristas e passageiros.'} />
            <ProductsElement image={PolimentoAutomotivo} title={'Polimento Automotivo'} description={'O polimento automotivo é um procedimento técnico que visa restaurar o brilho e a uniformidade da pintura do veículo, removendo imperfeições superficiais como riscos, marcas de chuva ácida, manchas e a oxidação causada pelo tempo. Dê ao seu veículo o melhor brilho possível! Com o polimento técnico, seu carro ganha uma aparência renovada e um brilho excepcional.'} />
            <ProductsElement image={PolimentoDeFarol} title={'Polimento de Farol'} description={'O polimento de farol é um procedimento que visa restaurar a transparência e a eficiência dos faróis do veículo. Com o tempo, os faróis podem se tornar opacos, amarelados ou riscados devido à exposição constante ao sol, poeira, poluição e outros agentes ambientais. Essa opacidade não só compromete a estética do carro, mas também reduz a visibilidade durante a condução noturna, afetando a segurança.'} />
            <ProductsElement image={RevitalizaçãoDePlasticos} title={'Revitalização de Plásticos'} description={'A revitalização de plásticos automotivos é um processo destinado a restaurar a aparência original de componentes plásticos, como para-choques, retrovisores, molduras e painéis, que podem se desgastar com o tempo devido à exposição ao sol, chuva, poluição e outros fatores ambientais. Esses elementos, quando não tratados, podem desbotar, ressecar e até apresentar rachaduras, comprometendo a estética do veículo.'} />
            <ProductsElement image={VitrificaçãoDePlásticos} title={'Vitrificação de Plásticos'} description={'A vitrificação de plásticos é uma técnica avançada de proteção e embelezamento dos componentes plásticos do veículo, tanto internos quanto externos. Esse processo envolve a aplicação de um revestimento cerâmico especial que forma uma camada protetora rígida, sobre a superfície dos plásticos. Essa camada oferece uma proteção duradoura contra os danos causados por fatores ambientais, além de realçar a aparência dos plásticos, conferindo-lhes um acabamento brilhante e renovado.'} />
            <ProductsElement image={VitrificaçãoFarol} title={'Vitrificação de Faróis'} description={'A vitrificação de faróis é um processo avançado de proteção que envolve a aplicação de um revestimento cerâmico nos faróis do veículo. Esse revestimento cria uma camada protetora, semelhante ao vidro, que não só restaura a aparência dos faróis, mas também oferece uma proteção duradoura contra diversos fatores que podem comprometer sua funcionalidade e estética, como os raios UV, sujeira, poluição e danos físicos leves.'} />
            <ProductsElement image={VitrificaçãoDePintura} title={'Vitrificação de Pintura'} description={'A vitrificação de pintura é um processo avançado de proteção automotiva que utiliza um revestimento cerâmico para criar uma camada protetora sobre a pintura do veículo. Esse tratamento é projetado para oferecer uma proteção duradoura contra diversos agentes externos, além de melhorar a aparência da pintura, deixando com um alto brilho e facilitando a manutenção do veículo.'} />
        </div>
    )
}

export default Products